### PR TITLE
Update R-bundle-Bioconductor-3.2-foss-2016a-R-3.2.3.eb

### PR DESCRIPTION
**Pull request by verdurin**
Add `penalized`, required by `sigaR`

### CODE REVIEW

**Comment by boegel** [comment]
@verdurin: this is already in `R-3.2.3-foss-2016a.eb`, so I think you need to run this with the easyconfig from `develop` to install the missing extensions (see also http://easybuild.readthedocs.org/en/latest/Partial_installations.html#partial-installation-skip)

```
eb R-3.2.3-foss-2016a.eb --skip --force
```

**Comment by verdurin** [comment]
Too many missing deps for this when trying with foss/2015b:

```
[adam@marcel verdurin-easyconfigs]$ eb R-3.2.3-foss-2016a.eb --skip --force --try-toolchain=foss,2015b
== temporary log file in case of crash /tmp/eb-qWoDvW/easybuild-uAjdMP.log
== processing EasyBuild easyconfig /tmp/eb-qWoDvW/tweaked_easyconfigs/R-3.2.3-foss-2015b.eb
== building and installing R/3.2.3-foss-2015b...
== fetching files...
== creating build dir, resetting environment...
== FAILED: Installation ended unsuccessfully (build directory: /home/adam/.local/easybuild/build/R/3.2.3/foss-2015b): build failed (first 300 chars): Missing modules for one or more dependencies: ncurses/6.0-foss-2015b, libpng/1.6.21-foss-2015b, libjpeg-turbo/1.4.2-foss-2015b, cURL/7.47.0-foss-2015b, libxml2/2.9.3-foss-2015b, GDAL/2.0.2-foss-2015b, PROJ/4.9.2-foss-2015b
== Results of the build can be found in the log file /tmp/eb-qWoDvW/easybuild-R-3.2.3-20160311.124031.EQHbf.log
ERROR: Build of /tmp/eb-qWoDvW/tweaked_easyconfigs/R-3.2.3-foss-2015b.eb failed (err: 'build failed (first 300 chars): Missing modules for one or more dependencies: ncurses/6.0-foss-2015b, libpng/1.6.21-foss-2015b, libjpeg-turbo/1.4.2-foss-2015b, cURL/7.47.0-foss-2015b, libxml2/2.9.3-foss-2015b, GDAL/2.0.2-foss-2015b, PROJ/4.9.2-foss-2015b')
```

**Comment by boegel** [comment]
@verdurin: no need for `--try-toolchain`, `R-3.2.3-foss-2015b.eb` is there in `develop` (deps got updated with the `foss/2016a` bump

**Comment by verdurin** [comment]
Closing, because this is redundant.

**Pull request closed without merging**
