### PR TITLE
Bump to OpenMPI to 5.0.3, PMIx to 5.0.2

### PR DESCRIPTION
**Pull request by bartoldeman**
`OpenMPI-5.0.x_add_atomic_wmb.patch` is obsolete now

### CODE REVIEW

**Comment by bartoldeman** [comment]
looks like github doesn't like this, but through no fault of my own I think, this PR just needs a merge/rebase from develop.

**Comment by boegel** [comment]
@bartoldeman I'm happy to merge this if you think it's fine?

**Comment by bartoldeman** [comment]
it's fine with me!

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
